---
brew:
  brew:
    - awscli
    - bash-completion
    - coreutils
    - mackup
    - shellcheck
  cask:
    - 1password
    - adobe-creative-cloud
    - aerial
    - brave-browser
    - dropbox
    - istat-menus
    - iterm2
    - kaleidoscope
    - muzzle
    - rectangle
    - slack
    - spotify
    - visual-studio-code
    - vlc

mackup:
  storage:
    engine: dropbox
  applications_to_sync:
    - 1password-4
    - aws
    - bash
    - git
    - iterm2
    - kaleidoscope
    - spotify
    - ssh
    - vlc

system:
  defaults:
    .GlobalPreferences:
      # System Preferences > General
      # Appearance (image selection)
      - { key: AppleInterfaceStyle, type: string, value: Dark }

      # System Preferences > Acessibility > Display > Cursor
      # Shake mouse pointer to locate (checkbox)
      - { key: CGDisableCursorLocationMagnification, type: bool, value: true }

      # System Preferences > Keyboard
      # Enable full keyboard access for all controls (e.g. enable Tab in modal dialogs)
      - { key: AppleKeyboardUIMode, type: integer, value: 3 }
      # Disable smart quotes and dashes (hidden)
      - { key: NSAutomaticQuoteSubstitutionEnabled, type: bool, value: false }
      - { key: NSAutomaticDashSubstitutionEnabled, type: bool, value: false }
      # Disable auto-correct (hidden)
      - { key: NSAutomaticSpellingCorrectionEnabled, type: bool, value: false }
      # Disable press-and-hold for keys in favor of key repeat (hidden)
      - { key: ApplePressAndHoldEnabled, type: bool, value: false }
      # Set a blazingly fast keyboard repeat rate (hidden)
      - { key: KeyRepeat, type: integer, value: 2 }

      # System Preferences > Mouse
      # Scroll direction: natural (checkbox)
      - { key: com\.apple\.swipescrolldirection, type: bool, value: false }

      # Other hidden preferences
      # Speed up window resize animations
      - { key: NSWindowResizeTime, type: float, value: 0.001 }
      # Expand save panel by default
      - { key: NSNavPanelExpandedStateForSaveMode, type: bool, value: true }
      - { key: NSNavPanelExpandedStateForSaveMode2, type: bool, value: true }
      # Expand print panel by default
      - { key: PMPrintingExpandedStateForPrint, type: bool, value: true }
      - { key: PMPrintingExpandedStateForPrint2, type: bool, value: true }
      # Save to disk (not to iCloud) by default
      - { key: NSDocumentSaveNewDocumentsToCloud, type: bool, value: false }

    # System Preferences > Dock
    com.apple.dock:
      # Size (slider)
      - { key: tilesize, type: float, value: 43 }
      # Magnification (slider)
      - { key: largesize, type: integer, value: 48 }
      # Magnification (checkbox)
      - { key: magnification, type: bool, value: true }
      # Automatically hide and show the Dock (checkbox)
      - { key: autohide, type: bool, value: true }
      # Show recents in Dock (checkbox)
      - { key: show-recents, type: bool, value: false }
      # Delay (hidden)
      - { key: autohide-delay, type: integer, value: 0 }
      # Semi transparent dock icons for hidden apps (hidden)
      - { key: showhidden, type: bool, value: true }
      # Remove all apps (user action)
      - { key: persistent-apps, type: json, value: [{}] }
      # Add new apps (user action)
      - { key: persistent-apps.0, type: json, value: { "tile-data": { "file-data": { "_CFURLString": "/Applications/Brave Browser.app", "_CFURLStringType": 0 } } } }
      - { key: persistent-apps.1, type: json, value: { "tile-data": { "file-data": { "_CFURLString": "/Applications/Spotify.app", "_CFURLStringType": 0 } } } }
      - { key: persistent-apps.2, type: json, value: { "tile-data": { "file-data": { "_CFURLString": "/Applications/Slack.app", "_CFURLStringType": 0 } } } }
      - { key: persistent-apps.3, type: json, value: { "tile-data": { "file-data": { "_CFURLString": "/Applications/Visual Studio Code.app", "_CFURLStringType": 0 } } } }
      - { key: persistent-apps.4, type: json, value: { "tile-data": { "file-data": { "_CFURLString": "/Applications/iTerm.app", "_CFURLStringType": 0 } } } }

    # Menu bar
    com.apple.systemuiserver:
      # Remove apps
      - { key: menuExtras, type: json, value: [{}] }
      # Add apps
      - { key: menuExtras.0, type: string, value: /System/Library/CoreServices/Menu Extras/Battery.menu }
      - { key: menuExtras.1, type: string, value: /System/Library/CoreServices/Menu Extras/Bluetooth.menu }
      - { key: menuExtras.2, type: string, value: /System/Library/CoreServices/Menu Extras/AirPort.menu }
      - { key: menuExtras.3, type: string, value: /System/Library/CoreServices/Menu Extras/Volume.menu }

    ByHost/com.apple.systemuiserver.UUID:
      - { key: dontAutoLoad, type: json, value: [ "/System/Library/CoreServices/Menu Extras/Clock.menu" ] }

    # System Preferences > Security & Privacy
    com.apple.screensaver:
      # Require password (checkbox)
      - { key: askForPassword, type: integer, value: 1 }
      # Require password (dropdown)
      - { key: askForPasswordDelay, type: float, value: 60 }

    # System Preferences > Mouse
    com.apple.driver.AppleBluetoothMultitouch.mouse:
      # Secondary click (checkbox)
      - { key: MouseButtonMode, type: string, value: TwoButton }

    # System Preferences > Trackpad
    com.apple.driver.AppleBluetoothMultitouch.trackpad:
      # Tap to click (checkbox)
      - { key: Clicking, type: integer, value: 1 }

    # System Preferences > Time Machine
    com.apple.TimeMachine:
      # Prevent Time Machine from prompting to use new hard drives as backup volume
      - { key: DoNotOfferNewDisksForBackup, type: bool, value: true }

    # Other hidden preferences
    com.apple.frameworks.diskimages:
      # Disable disk image verification
      - { key: skip-verify, type: bool, value: true }
      - { key: skip-verify-locked, type: bool, value: true }
      - { key: skip-verify-remote, type: bool, value: true }

    com.apple.LaunchServices:
      # Disable the "Are you sure you want to open this application?"x dialog
      - { key: LSQuarantine, type: bool, value: false }

    # Finder
    com.apple.finder:
      # Show hidden files
      - { key: AppleShowAllFiles, type: string, value: YES }
      # Show status bar
      - { key: NewWindowTarget, type: string, value: PfHm }
      # Show status bar
      - { key: ShowStatusBar, type: bool, value: true }
      # Disable the warning when changing a file extension
      - { key: FXEnableExtensionChangeWarning, type: bool, value: false }
      # When performing a search, search the current folder by default
      - { key: FXDefaultSearchScope, type: string, value: SCcf }
      # Use column view in all Finder windows by default
      - { key: FXPreferredViewStyle, type: string, value: clmv }
      # Show status bar
      - { key: FXPreferredGroupBy, type: string, value: Kind }
      # Allow text selection in Quick Look
      - { key: QLEnableTextSelection, type: bool, value: true }
      # Show icons for hard drives, servers, and removable media on the desktop
      - { key: ShowHardDrivesOnDesktop, type: bool, value: true }
      - { key: ShowMountedServersOnDesktop, type: bool, value: true }
      # Arrange by
      - { key: DesktopViewSettings.IconViewSettings.arrangeBy, type: string, value: grid }
      - { key: FK_StandardViewSettings.IconViewSettings.arrangeBy, type: string, value: grid }
      - { key: StandardViewSettings.IconViewSettings.arrangeBy, type: string, value: grid }
      # Grid spacing
      - { key: DesktopViewSettings.IconViewSettings.gridSpacing, type: integer, value: 40 }
      - { key: FK_StandardViewSettings.IconViewSettings.gridSpacing, type: integer, value: 40 }
      - { key: StandardViewSettings.IconViewSettings.gridSpacing, type: integer, value: 40 }
      # Icon size
      - { key: DesktopViewSettings.IconViewSettings.iconSize, type: integer, value: 44 }
      - { key: FK_StandardViewSettings.IconViewSettings.iconSize, type: integer, value: 44 }
      - { key: StandardViewSettings.IconViewSettings.iconSize, type: integer, value: 44 }
      # Label on bottom
      - { key: DesktopViewSettings.IconViewSettings.labelOnBottom, type: bool, value: false }
      - { key: FK_StandardViewSettings.IconViewSettings.labelOnBottom, type: bool, value: false }
      - { key: StandardViewSettings.IconViewSettings.labelOnBottom, type: bool, value: false }
      # Text size
      - { key: DesktopViewSettings.IconViewSettings.textSize, type: integer, value: 10 }
      - { key: FK_StandardViewSettings.IconViewSettings.textSize, type: integer, value: 10 }
      - { key: StandardViewSettings.IconViewSettings.textSize, type: integer, value: 10 }

    com.apple.desktopservices:
      # Avoid creating .DS_Store files on network volumes
      - { key: DSDontWriteNetworkStores, type: bool, value: true }

  security:
    # System Preferences > Security & Privacy > General > Allow apps downloaded from: Anywhere
    disable_gatekeeper: true


  labels:
    # System Preferences > Sharing > Computer Name
    computer_names:
      - { key: ComputerName, value: USER-macbook }
      - { key: LocalHostName, value: USER-macbook }

  power:
    # System Preferences > Energy Saver
    power_settings_all:
      - { key: disksleep, value: 10 }
      - { key: womp, value: 0 }
      - { key: autorestart, value: 0 }
      - { key: halfdim, value: 0 }
      - { key: sms, value: 0 }

    # System Preferences > Energy Saver > Battery
    power_settings_battery:
      - { key: displaysleep, value: 5 }
      - { key: sleep, value: 10 }
      - { key: powernap, value: 0 }
      - { key: lessbright, value: 1 }

    # System Preferences > Energy Saver > Power Adaptor
    power_settings_charger:
      - { key: displaysleep, value: 10 }
      - { key: sleep, value: 0 }
      - { key: powernap, value: 1 }
      - { key: lessbright, value: 0 }

misc:
  font:
    name: SourceCodePro-Regular.otf
    download: https://github.com/adobe-fonts/source-code-pro/archive/release.zip
    path: source-code-pro-release/OTF

  screensaver:
    defaults:
      ByHost/com.apple.screensaver.UUID:
        - { key: "moduleDict:displayName", type: string, value: Aerial }
        - { key: "moduleDict:moduleName", type: string, value: Aerial }
        - { key: "moduleDict:path", type: string, value: "~/Library/Screen Savers/Aerial.saver" }
        # Start after (dropdown)
        - { key: idleTime, type: integer, value: 120 }

apps:
  brave:
    set_as_default: true
    defaults:
      com.brave.Browser:
        # Disable the all too sensitive backswipe on trackpads and Magic Mouse
        - { key: AppleEnableSwipeNavigateWithScrolls, type: bool, value: false }
        - { key: AppleEnableMouseSwipeNavigateWithScrolls, type: bool, value: false }

  iterm2:
    import_style: true
    shell_integration: true
    defaults:
      com.googlecode.iterm2:
        # Don’t display the annoying prompt when quitting iTerm
        - { key: PromptOnQuit, type: bool, value: false }
        # Don’t display the annoying update prompt
        - { key: SUEnableAutomaticChecks, type: bool, value: false }
