#!/bin/bash

# User editable
OSX_COMPUTER_NAME="Ben's Lappy"
OSX_HOST_NAME="laptop-benwhite"
OSX_HOME_DIR="/Volumes/Home/Users/benwhite"
USER_NAME="Ben White"
USER_EMAIL="hello@bemm.com.au"
GIT_REMOTE="git@github.com:d3v1an7/fresh.git"

# Hard coded
COLOUR_PASS=$(tput setaf 2)
COLOUR_INFO=$(tput setaf 4)
COLOUR_WARN=$(tput setaf 3)
COLOUR_ERROR=$(tput setaf 1)
COLOUR_RESET=$(tput sgr0)

desired_brew_formulae=(
  'coreutils' # GNU core utilities (those that come with OS X are outdated)
  'node'
  'git'
  'ack'
  'awscli'
  'bash'
  'bash-completion'
  'brew-cask'
  'curl'
  # PHP/Composer failing on Xcode 6 beta
  #'php55-intl' # Composer 
  #’josegonzalez/php/composer' # Composer
  'libevent'
  'openssl'
  'packer'
  'vim'
  'wget'
)

desired_casks=(
  'adium'
  'adobe-creative-cloud' # Manual install
  'atom'
  'cakebrew'
  'cloud'
  'dashlane'
  'dropbox'
  'firefox'
  'gas-mask'
  'google-chrome'
  'heroku-toolbelt'
  'hipchat'
  'ios7-screensaver'
  'istat-menus'
  'iterm2'
  'kaleidoscope'
  'mpeg-streamclip'
  'origin'
  'prefs-editor'
  'sequel-pro'
  'skype'
  'sonos'
  'spotify'
  'steam'
  'sublime-text'
  'teamviewer' # Manual install
  'utorrent' # Manual install
  'virtualbox' # Manual install
  'vagrant'
  'vagrant-manager'
)

desired_taps=(
  'caskroom/cask' # Casks
  'homebrew/binary' # Packer
  'homebrew/versions' # Composer
  'josegonzalez/homebrew-php' # Composer
)
