#!/bin/bash

run_brew() {
  # Check for Homebrew
  if type_exists 'brew'; then
    echo "Updating Homebrew..."
    brew update
    [[ $? ]] && e_success "Done"
    echo

    echo "Updating any existing Homebrew formulae..."
    brew upgrade
    [[ $? ]] && e_success "Done"
    echo

    echo "Checking status of desired Homebrew formulae..."
    local list_formulae
    local -a missing_formulae

    for index in ${!desired_brew_formulae[*]}
    do
      if ! formula_exists ${desired_brew_formulae[$index]}; then
        # Store the name (and options) of every missing formula
        missing_formulae=("${missing_formulae[@]}" "${desired_brew_formulae[$index]}")
      fi
    done

    if [[ "$missing_formulae" ]]; then
      # Convert the array of missing formula into a list of space-separate strings
      list_formulae=$( printf "%s " "${missing_formulae[@]}" )

      echo "Installing missing Homebrew formulae..."
      # Install all missing formulae
      brew install $list_formulae

      [[ $? ]] && e_success "Done"
    fi

    # Remove outdated versions from the Cellar
    echo
    echo "Cleaning up outdated versions..."
    brew cleanup
    e_success "Done"

  else
    printf "\n"
    e_error "Error: Homebrew not found."
    printf "Aborting...\n"
    exit
  fi

}
