#!/bin/bash

set_home_directory() {
  if [[ $OSX_HOME_DIR != $HOME ]]; then
    clear
    title_info "Set new home directory"
    echo "It looks like you want to move your home directory!"
    echo
    echo "Current home: ${HOME}"
    echo "New home: ${OSX_HOME_DIR}"
    echo
    read -p "Are you sure ${OSX_HOME_DIR} is correct? (y/n) " -n 1 user_input
    echo
    if [[ $user_input =~ ^[Nn]$ ]]; then
      title_info "Set home directory"
      read -p  "User home: " input
      OSX_HOME_DIR="${input:-$OSX_HOME_DIR}"
      set_home_directory
    elif [[ $user_input =~ ^[Yy]$ ]]; then
      sudo dscl . -change Users/$USER NFSHomeDirectory $HOME $OSX_HOME_DIR
      sudo mv $HOME/* $OSX_HOME_DIR
      title_pass "All done. Great sucess!"
      echo "Logging out for settings to take effect."
      logout
    else
      title_error "Invalid input"
    fi
  fi
}