#!/bin/bash

link() {
  # Force create/replace the symlink
  ln -fs "${FRESH_DIR}/${1}" "${HOME}/${2}"
  e_success "${1} -> ${2}"
}

mirrorfiles() {
  # Create the necessary symbolic links between the `.dotfiles` and `HOME`
  # directory. The `bash_profile` sources other files directly from the
  # `.dotfiles` repository.
  link "shell/bashrc"       ".bashrc"
  link "shell/bash_profile" ".bash_profile"
  link "shell/curlrc"       ".curlrc"
  link "shell/inputrc"      ".inputrc"
}