#!/bin/bash

run_npm() {
  # Check for npm
  if type_exists 'npm'; then

    # Fix permissions credit: http://stackoverflow.com/a/19355874
    sudo chown -R $USER /usr/local

    echo
    echo "Installing Node.js packages..."

    # List of npm packages
    local packages="bower grunt-cli"

    # Install packages globally
    npm install $packages --global --loglevel warn > /dev/null

    [[ $? ]] && e_success "Done"
  else
    printf "\n"
    e_error "Error: npm not found."
    printf "Aborting...\n"
    exit
  fi
}
