#!/bin/bash

run_taps() {
  # Check for Homebrew
  if type_exists 'brew'; then
    local list_formulae
    local -a missing_formulae

    for index in ${!desired_taps[*]}
    do
      if ! tap_exists ${desired_taps[$index]}; then
        # Store the name (and options) of every missing formula
        missing_formulae=("${missing_formulae[@]}" "${desired_taps[$index]}")
      fi
    done

    if [[ "$missing_formulae" ]]; then
      # Convert the array of missing formula into a list of space-separate strings
      list_formulae=$( printf "%s " "${missing_formulae[@]}" )

      echo "Installing missing Homebrew formulae..."
      # Install all missing formulae
      brew tap $list_formulae

      [[ $? ]] && e_success "Done"
    fi

  else
    printf "\n"
    e_error "Error: Homebrew not found."
    printf "Aborting...\n"
    exit
  fi

}
