name: CD
on: [push]
#   pull_request:
#     types:
#       - closed
#     branches:
#       - main
concurrency: production
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: '0'
      - name: Determine semver
        id: semver
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAJOR_STRING_TOKEN: major
          MINOR_STRING_TOKEN: minor
          PATCH_STRING_TOKEN: patch
          NONE_STRING_TOKEN: skip
          DRY_RUN: true
      - name: Install Poetry
        run: pip install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: '.python-version'
          cache: 'poetry'
      - name: Set new version for CLI tool
        run: poetry version ${{ steps.semver.outputs.new_tag }}
      - name: Install dependencies
        run: poetry install --no-dev
      - name: Build CLI tool
        run: poetry build --format=sdist
      - name: Add semver tag
        run: |
          git tag ${{ steps.semver.outputs.new_tag }}
          git push --tags
      - name: Create GitHub release
        run: gh release create ${{ steps.semver.outputs.new_tag }} ./dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Bump Homebrew formula
        uses: mislav/bump-homebrew-formula-action@v2
        with:
          formula-name: macos-fresh
          formula-path: Formula/macos-fresh.rb
          homebrew-tap: d3v1an7/homebrew-taps
          base-branch: main
          download-url: https://github.com/d3v1an7/macos-fresh/releases/download/${{ steps.semver.outputs.new_tag }}/macos_fresh-${{ steps.semver.outputs.new_tag }}.tar.gz
          commit-message: |
            {{formulaName}} {{version}}
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}

