name: CD
on:
  push:
    tags:
      - "*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: '.python-version'
      - name: Install Poetry
        run: pip install --root-user-action=ignore poetry
      - name: Set new version for CLI tool based on tag
        run: poetry version ${{ github.ref }}
      - name: Install dependencies
        run: poetry install --no-dev
      - name: Build CLI tool
        run: poetry build --format=sdist
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/
