name: CI
on:
  push:
    branches-ignore:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version-file: '.python-version'
          cache: 'poetry'
      - run: pip install --root-user-action=ignore poetry
      - run: poetry install
      - run: poetry run flake8 ./fresh
      - run: poetry run black ./fresh --check